### ISSUE TITLE
Adicionar logo via customizer

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/aspta_sage#1]
Iniciei o processo, o customizer apresenta a posibilidade de fazer upload do logo, mas o logo não aparece no cabeçalho.

Para testar usei o seguinte código no debug-bar-console:

var_dump(get_theme_mods()); 
var_dump( get_theme_mod( 'aspta_sage_upload_logo' ));

fonte: https://codex.wordpress.org/Theme_Customization_API

arquivos:

templates/hearder.php - display logo
functions.php - configure customizer

**Comment by rodineicosta** [comment]
Na nova proposta adicionada (_branch: wp-aspta_) o **logotipo** é inserido manualmente através do painel de administração do WP.
