### ISSUE TITLE
fazer css da home

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/aspta_sage#16]

**Comment by rodineicosta** [comment]
**CSS da Home** iniciada, com layout responsivo e arquivos adicionados em novo _Branch_ (ws-astpa) para testes. Segue anexo print do projeto em _localhost_.
![aspta_home](https://cloud.githubusercontent.com/assets/15682777/16977700/1a553ad8-4e2e-11e6-9e77-441fb1a57987.jpeg)

**Comment by rodineicosta** [comment]
**CSS da Home** alterada _código de funções reorganizado_ e demais arquivos de templates, fontes, imagens e estilos, reorganizados na pasta _/assets_ no _Branch (ws-astpa)_ para testes.

**Comment by rodineicosta** [comment]
**CSS da Home** alterada com slideshow em funcionamento e publicações em destaque com as referidas imagens destacadas, sendo adicionada a imagem padrão para _"no-thumbnail"_ no _Branch (master)_ para testes.

![aspta-home](https://cloud.githubusercontent.com/assets/15682777/17267831/b3608b1a-55ea-11e6-97c0-422aec0522ad.png)
