### ISSUE TITLE
fazer css das edições anteriores

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/aspta_sage#17]
ficar atento a transparencia das imagens ver issue #15 

estamos pensando em usar isso aqui:

http://masonry.desandro.com/

**Comment by rodineicosta** [comment]
Há dois modelos de páginas destinadas a esse item do projeto. Qual das duas utilizar?
Seguem os anexos.

**Comment by rodineicosta** [comment]
![revista-edicoes-anteiores](https://cloud.githubusercontent.com/assets/15682777/21165151/b877c5fe-c184-11e6-8cb4-7c522f3c3501.png)

**Comment by rodineicosta** [comment]
![revista-edicoes-anteiores 1](https://cloud.githubusercontent.com/assets/15682777/21165171/e4d66df8-c184-11e6-8fa9-1f96933b9833.png)

**Comment by rodineicosta** [comment]
Preciso de ajuda para que o plugin IssueM funcione na minha instalação local, para que eu possa terminar a codificação do layout dessa página.

**Comment by cabelotaina** [comment]
acredito que seja este aqui https://github.com/redelivre/aspta_sage/issues/17#issuecomment-266907632 - a segunda imagem que vc anexou.

**Comment by jacsonp** [comment]
Ajuda com IssueM/Redelivre realizada

**Comment by rodineicosta** [comment]
Feito! Porém, a proporção do tamanho das imagens em miniatura são definidas na configuração do plugin, onde as mesmas necessitam passar por regeneração após alteração através de outro plugin indicado pelo IssueM nessa mesma página.

**Comment by cabelotaina** [comment]
@rodineicosta essa issue já pode ser fechada? Tem algo que eu posso ajudar?

**Comment by rodineicosta** [comment]
@cabelotaina, como eu disse anteriormente, para que as imagens fiquem da forma do projeto original, devem ser configuradas no painel de controle e regeneradas através de um plugin indicado na página de configurações. Devemos definir se ficam no tamanho que está no momento ou se instalamos esse novo plugin para aumenta-las. Daí, podemos fechar.
