### ISSUE TITLE
Menu inferior encavalando

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#19]
O menu inferior do site está encavalado conforme imagem abaixo
![menu-inferior-aspta-encavalado](https://cloud.githubusercontent.com/assets/4163139/20564753/c9602aa6-b175-11e6-836c-699adfe93343.png)

**Comment by rodineicosta** [comment]
@thalitasejanes e @cabelotaina, precisamos definir o layout do rodapé.

**Comment by rodineicosta** [comment]
Menu de rodapé sendo exibido, conforme o projeto visual original.
