### ISSUE TITLE
Biblioteca interna - Tipos de materiais desalinhado

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#20]
Na página interna da biblioteca, quando já fizemos uma primeira seleção de itens para busca, a primeira parte sobre "Tipos de materiais" as opções estão desalinhadas em relação ao checkbox conforme imagem abaixo: 

![biblioteca-aspta-interna-tiposdemateriais-desalinhado](https://cloud.githubusercontent.com/assets/4163139/20565101/4a31bc0c-b177-11e6-8aee-7dd4c63dda79.png)

**Comment by rodineicosta** [comment]
Itens realinhados.
