### ISSUE TITLE
Busca-categoria está sem estilo

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#21]
É preciso fazer o estilo da busca. 
Testei clicando na capa diretamente em uma categoria e abriu esta página da imagem abaixo, testei com as categorias notícias e experiencias e a página ficou assim: 
![busca-categoria-sem-estilo](https://cloud.githubusercontent.com/assets/4163139/20565303/32ca28d2-b178-11e6-89b7-f5d6bd70e8ee.png)

**Comment by anapaulabrasa** [comment]
Sugiro reproduzir o estilo da lista de Notícias (http://aspta.beta.redelivre.org.br/noticias/) em listas de posts (demais categorias) e em resultados de busca (exemplo: http://aspta.beta.redelivre.org.br/?s=borborema).

O estilo da página Notícias está bastante organizado com a informações de post, mantendo o alinhamento de imagem e texto.

**Comment by rodineicosta** [comment]
Feito. Porém, ainda é necessário formatar a paginação no fim da página.

**Comment by cabelotaina** [comment]
Por enquanto colocamos um sistema de paginação sem numeros apenas com um link que permite ver as mais antigas, por conta de que não entedemos como fazer a paginção nas paginas de tags.

**Comment by rodineicosta** [comment]
Testei agora e a paginação numerada está funcionando. Não sei exatamente o que houve quando testei anteriormente. Encerrarmos essa Issue.

**Comment by cabelotaina** [comment]
@rodineicosta legal demais
