### ISSUE TITLE
Busca biblioteca com imagem não redimensiona

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#22]
Percebi que se o post não tem imagem fica uma padão bem formatada, no entanto, nesta busca que eu fiz na biblioteca com o "Tipo de material" seleção "experiência" e que tinha uma imagem destacada, ela se sobrepõe ao texto. é preciso acertar isto, conforme imagem abaixo: 

![busca-biblioteca-resultado com imagem nao reduz](https://cloud.githubusercontent.com/assets/4163139/20565390/8a3f3788-b178-11e6-8e71-47a75f4daeb3.png)

**Comment by rodineicosta** [comment]
Feito.
