### ISSUE TITLE
Notícias relacionadas: não está puxando

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#23]
Conforme pode ser visto na imagem abaixo, em qualquer pesquisa que se faça, mesmo em posts que tem várias notícias relacionadas, estas não estão sendo puxadas: 

![noticias-relacionadas-nao-esta-puxando](https://cloud.githubusercontent.com/assets/4163139/20565511/f1d0b46c-b178-11e6-90a6-790b0d6619b7.png)

**Comment by rodineicosta** [comment]
Nesse caso, usaremos plugin ou vamos codar no braço?

**Comment by rodineicosta** [comment]
Feito, no braço.
