### ISSUE TITLE
Botões de compartilhamento não funcionam

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#24]
Os botões para compartilhar uma noítcia nao estão funcionando, conforme pode ser visto neste linque: http://aspta.beta.redelivre.org.br/2016/06/27/lei-de-sementes-nicaragua/ e ilustrada na imagem abaixo: 

![botoes-compartilhamento-nao-funcionam](https://cloud.githubusercontent.com/assets/4163139/20565562/2d2327a2-b179-11e6-8d5c-e6ad1ebf7852.png)

**Comment by rodineicosta** [comment]
O plugin de compartilhamento a ser utilizado precisa ser definido.

**Comment by jacsonp** [comment]
Não rola fazer igual ao guarani?

**Comment by rodineicosta** [comment]
Botões de compartilhamento para facebook e Google Plus em funcionamento. Não encontrei informações sobre botão de compartilhamento para YouTube, apenas para inscrição em Canal. Sugiro alterar para outra rede social.

**Comment by cabelotaina** [comment]
@thalitasejanes faça um botao do twitter.

**Comment by thalitasejanes** [comment]
![twitter](https://cloud.githubusercontent.com/assets/4115304/21107351/89a2423e-c078-11e6-9012-d7576013168c.png)

**Comment by anapaulabrasa** [comment]
mas nada a ver botão de compartilhamento do Youtube, né? Ele cai e entra o Tweeter, é isso?

**Comment by rodineicosta** [comment]
Feito!
