### ISSUE TITLE
Página Quem somos desconfigurada

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#25]
A página "Quem somos" precisa ser desenvolvida, todas as orientaçòes estão no linque: http://aspta.beta.redelivre.org.br/quem-somos/

**Comment by rodineicosta** [comment]
Feito.

**Comment by rodineicosta** [comment]
Falta definir se o código será inserido por sidebar, widget ou direto na página conforme iniciado.
Os botões ainda não foram linkados.
