### ISSUE TITLE
Organizar menu, conforme proposta da Adriana

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#27]
@thalitasejanes 

A partir do Menu:

1-      Quem somos
Vamos manter todos os itens que já estão no ar:
a-      Conselho administrativo
b-      Equipe Executiva
c-       Agências Parceiras (Esse item é = Apoiadores, manteremos como está. Queremos aqui diferenciar Apoiadores Atuais | Já apoiou a AS-PTA)
d-      Planos Trienais
e-      Relatórios de Atividades
f-       Estatutos e Atas
g-      Demonstrações Financeiras
h-      Certidões e Títulos
i-        Licitações
 
2-      Em Linhas de Atuação vamos mudar para TEMAS DE INTERVENÇÃO e os subitens ficariam:
a-      Acesso a mercados
b-      Agrobiodiversidade
c-       Agrofloresta
d-      Construção do Conhecimento Agroecológico
e-      Criação Animal
f-       Financiamento da Transição Agroecológica
g-      Infância e Juventude
h-      Manejo da Água
i-        Manejo Ecológico dos Solos
j-        Monitoramento da transição Agroecológica
k-      Mulheres e Agroecologia
l-        Saúde e Alimentação
OBS:
- TIRAR Relações de Gênero e Geração
- Acrescentar TRANSGÊNICOS
- Ação em rede estará na barra no final da Home
- Programas locais está no quadro no centro da Home
Achamos que as duas últimas informações ficaram redundantes na página principal.
 
3-      Biblioteca
a-      Havíamos combinado de colocarmos os itens da Campanha na pesquisa. No mínimo, temos que acrescentar no tema de intervenção “Transgênicos”
b-      No meu computador, algumas palavras aparecem sem acentuação
c-       As imagens aparecem desorganizadas (em tamanhos diferentes e sobrepostas por textos)
d-      Ficamos preocupados com a aplicação do elemento da logomarca com as cores alteradas quando substitui as fotos
 
4-      Revista
a-      Sobre a Revista
b-      Próximas Chamadas
c-       Submeter artigo
d-      Assine

 
5-      Campanha
a-      Boletim
b-      GM Free Brazil
c-       Materiais de Campanha
d-      Monitoramento da CTNBio
e-      Transgênicos
 
6-      Entre em contato e Assine o Feed precisam estar no menu principal?

**Comment by rodineicosta** [comment]
Algumas considerações devem ser observadas quanto à disposição do menu e seus submenus;

Ocorre que, para melhor experiência de usuário, submenus não podem ser ativados com o posicionamento do ponteiro do mouse sobre o mesmo, pelo comportamento em dispositivos móveis. Do mesmo modo que o código utilizado (_Nav Walker Menu Bootstrap_) assume o link "#" desativado para o item superior quando existem submenus.

Para o caso de subpáginas, sugiro que os links sejam apresentados na página de origem, conforme o modelo adotado na página "_Quem Somos_".

Para o caso de submenus, sugiro que os mesmos sejam adotados onde o menu principal não direcione usuários para página, conforme o item "_Revista Agriculturas_".

Dessa forma, deveríamos reavaliar como seriam demonstrados os subitens dos itens "_Temas de Intervenção_", "_Biblioteca_" e "_Campanha Transgênicos_", no menu principal.

**Comment by thalitasejanes** [comment]
Pessoal esses submenus são nas páginas na sidebar de cada uma, não no menu principal.
