### ISSUE TITLE
Criar modelo da página com ícones/imagens 

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#28]
@thalitasejanes 

para a página Temas de intervenção

**Comment by thalitasejanes** [comment]
Tela com ícones
![temas-de-intervencao_novo](https://cloud.githubusercontent.com/assets/4115304/21076738/777e1b50-bf1a-11e6-8362-9cbb4ac694ef.png)

**Comment by thalitasejanes** [comment]
ícones em png
![icons](https://cloud.githubusercontent.com/assets/4115304/21076749/a38a0592-bf1a-11e6-8080-80eac8e6d0cb.png)

**Comment by cabelotaina** [comment]
Ficou lindão

**Comment by rodineicosta** [comment]
Feito.
