### ISSUE TITLE
Revisar biblioteca

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#29]
@cabelotaina 

Rever itens, conforme considerações por e-mail, corrigir títulos sem acentuação

**Comment by cabelotaina** [comment]
Onde consigo este email?

**Comment by rodineicosta** [comment]
@cabelotaina, acredito que @anapaulabrasa se refere ao texto que encontra-se no fim do documento "Refino do Site", no Google Docs.

**Comment by cabelotaina** [comment]
Em poucos minutos começando a revisão disso aqui.

**Comment by cabelotaina** [comment]
Eu li o email e não existe uma descrição de problemas com erros ortograficos, vou fechar essa issue, se houver mais infos favor reabrir e colocar aqui.
