### ISSUE TITLE
Página Campanha Transgênicos está quebrada

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#30]
@thalitasejanes 

Esta página será uma lista de ícones/imagens que necessita de desenho.

**Comment by thalitasejanes** [comment]
![campanha](https://cloud.githubusercontent.com/assets/4115304/21106116/f69b1bae-c073-11e6-8649-1ea8475506eb.png)

**Comment by thalitasejanes** [comment]
![icons2](https://cloud.githubusercontent.com/assets/4115304/21077122/f72b5488-bf26-11e6-97f5-bb81de921c48.png)

**Comment by rodineicosta** [comment]
Feito!
