### ISSUE TITLE
Captcha não funciona

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#32]
Nos comentários não tá rolando o captcha

![captchacomments](https://cloud.githubusercontent.com/assets/2422926/21110080/ff1ac9aa-c082-11e6-8e4f-8b0a8e9679fd.png)

**Comment by rodineicosta** [comment]
@cabelotaina, token é contigo ou com @jacsonp?

**Comment by cabelotaina** [comment]
uai o @jacsonp tem mais a manha mas nao sei como ele esta de tempo?

**Comment by jacsonp** [comment]
Permissões da pasta cache e temp dentro do plugin foram alteradas pelo jenkins, corrigido no beta.
