### ISSUE TITLE
Corrigir rede sociais do footer

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#33]
Deixar todos em branco e adicionar Vimeo e Twitter em anexo @rodineicosta 

![icon-twitter](https://cloud.githubusercontent.com/assets/4115304/21146441/ca7761b6-c138-11e6-9785-a0de93b815f4.png)
![icon-vimeo](https://cloud.githubusercontent.com/assets/4115304/21146442/ca7a6424-c138-11e6-8097-1534fd63b7b6.png)

**Comment by rodineicosta** [comment]
Feito!
