### ISSUE TITLE
Padronizar Sidebar do site

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#34]
modelo padrão de sidebar, 

destaco que as páginas **PROGRAMAS e CAMPANHA** tem os seus ultimos posts especifícos

![sidebar](https://cloud.githubusercontent.com/assets/4115304/21151127/854a21ae-c148-11e6-8eb1-e2dc4fd078e1.png)

**Comment by thalitasejanes** [comment]
@cabelotaina @rodineicosta o ícone da revista é o enviado no plugin issueM ao cadastrar uma revista nova, o mesmo que aparece na capa. ele vai mudar todo mês, conforme o usuario colocar uma nova revista atual.

**Comment by rodineicosta** [comment]
@cabelotaina algumas páginas precisam ter as sidebars definidas. A partir daí, é posicionamento no painel de controle de widgtes.

**Comment by jacsonp** [comment]
Podemos usar templates com sidebars diferenciadas ou selecionar a side na página (http://gabrieleromanato.name/wordpress-let-users-choose-their-sidebar-on-posts-and-pages-with-custom-values)

**Comment by cabelotaina** [comment]
Esperando modificações do @rodineicosta e revisão da @thalitasejanes

**Comment by thalitasejanes** [comment]
sobre a sidebar coloquei os linques da página atual que é a referência

as páginas que  contam com sub menu interno: [Quem somos](http://aspta.org.br/revista-agriculturas/), [Programas](http://aspta.org.br/programas/), [itens da Campanha](http://aspta.org.br/itens-de-campanha/materiais-de-campanha/) e [Revista](http://aspta.org.br/revista-agriculturas/).

as páginas que mostram o widget útimos posts especificos da seção: [Programas](url) (últimas dos programas) e os itens da [Campanha] (últimas da campanha)(http://aspta.org.br/itens-de-campanha/materiais-de-campanha/)

as demais páginas seguem o modelo desenhado com os widgets (blog em pratos limpos, revista agriculturas e últimos posts)

**Comment by anapaulabrasa** [comment]
Compartilhando aqui as páginas de Programas e de Campanha que devem apresentar o widget lateral de posts recentes específicos. 

PROGRAMAS - págs que devem conter o widget "Últimas deste Programa":

- [Programa Paraíba](http://aspta.beta.redelivre.org.br/programa-paraiba)
- [Programa de Agricultura Urbana](http://aspta.beta.redelivre.org.br/programa-de-agricultura-urbana)
- [Programa do Contestado](http://aspta.beta.redelivre.org.br/programas/programa-do-contestado/)


CAMPANHA TRANSGÊNICOS - págs que devem conter o widget "Últimos posts da Campanha":

- [Boletim](http://aspta.beta.redelivre.org.br/itens-de-campanha/boletim/) 
- [Gm Free Brazil](http://aspta.beta.redelivre.org.br/itens-de-campanha/gm-free-brazil/)
- [Materiais de campanha](http://aspta.beta.redelivre.org.br/itens-de-campanha/materiais-de-campanha/)
- [Monitoramento da CTNBio](http://aspta.beta.redelivre.org.br/itens-de-campanha/monitoramento-ctnbio/)
- [Transgênicos](http://aspta.beta.redelivre.org.br/itens-de-campanha/campanha-transgenicos/)

Aguardo implementação para realizar novos testes.
