### ISSUE TITLE
Programas Locais não aparecem listados na Home Page

### ISSUE THREAD

**Issue by rodineicosta** [redelivre/aspta_sage#36]
A sessão "Programas Locais" na Home Page não lista os três programas conforme o projeto original. É preciso rever o código.

**Comment by cabelotaina** [comment]
Alguém consegue descrever exatamente o que deve estar lá? @thalitasejanes @rodineicosta ?

**Comment by thalitasejanes** [comment]
São três programas locais e aparecem 2 na home apenas, precisa olhar no layout, estou apenas no celular agora, mas olhando na Aspta.org.br que está no ar é possível ver os programas.

**Comment by thalitasejanes** [comment]
No footer estão os programas

**Comment by rodineicosta** [comment]
Segue o projeto original da Home:
![home](https://cloud.githubusercontent.com/assets/15682777/21289084/b80a1e98-c47a-11e6-9dbc-72e71ad27fce.png)
