### ISSUE TITLE
Os links da sessão Campanha precisam ser revistos

### ISSUE THREAD

**Issue by rodineicosta** [redelivre/aspta_sage#37]
Os links nos banners da sessão "Campanha" estão redirecionando para os Programas Locais.

**Comment by cabelotaina** [comment]
Não sei o que fazer pois o texto encontrado nas páginas trata do tema que aparece na imagem. Realmente a @thalitasejanes teria que ver isso para a gente.

**Comment by thalitasejanes** [comment]
**polo da borborema** : https://www.facebook.com/polodaborborema/?fref=ts

**coletivo triunfo**: https://www.facebook.com/ColetivoTriunfo/?fref=ts

**produtos da gente**: http://aspta.org.br/2014/03/conheca-os-produtos-da-gente/
