### ISSUE TITLE
Inserir whatsapp no compartilhamento de notícias

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#38]
Comentário encaminhado pela Adriana ASP-TA
- botões de compartilhar - incluir whatsapp
envio abaixo os botões corrigidos no tamanho e com whatsapp

![twitter-share](https://cloud.githubusercontent.com/assets/4115304/21348452/65651c3a-c694-11e6-95e7-2e792093f414.png)
![google-share](https://cloud.githubusercontent.com/assets/4115304/21348449/65610906-c694-11e6-9b0e-80670c3d9faf.png)
![whats-share](https://cloud.githubusercontent.com/assets/4115304/21348451/65639d74-c694-11e6-99c1-a0991d426eed.png)
![facebook-share](https://cloud.githubusercontent.com/assets/4115304/21348450/65624244-c694-11e6-8895-887d5ae22354.png)

**Comment by cabelotaina** [comment]
Estou inserindo a lógica, @thalitasejanes vamos usar esses botões que estão na imagem acima mesmo ou você vai enviar novos, @rodineicosta quando eu terminar e @thalitasejanes responder ai tu arruma o código para ficar linão.

**Comment by cabelotaina** [comment]
Galera coloquei um botão do whats mas com uma imagem do twitter e eles continuam na horizontal, essa bronca é do @rodineicosta

**Comment by cabelotaina** [comment]
Para ver que o botão tosco esta lá e funciona é necessario usar celular, não funciona este recurso no browser. Alguém sabe fazer para navegador e abrir no whatsapp web :smile:

**Comment by thalitasejanes** [comment]
atentem que eu corrigi o tamanho de todos os botões

**Comment by cabelotaina** [comment]
Mas é deste print que o @rodineicosta tem que tirar os botões certo?

**Comment by rodineicosta** [comment]
Compartilhamento para WhatsApp somente em mobile. O código pode estar ali em telas maiores, porém não irá redirecionar para o WhtsApp Web. Software proprietário é assim mesmo, não temos possibilidades de fazer funcionar como todos gostariam. Dessa forma, proponho que o botão do WhatsApp só apareça em telas mobile. Assim, os botões atuais permanecem como estão e o de compartilhamento para o WhatsApp se junta a eles nas telas menores.

**Comment by rodineicosta** [comment]
Feito!
