### ISSUE TITLE
Imagem do slider distorcida

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#39]
Temos alguma idéia de como resolver a questão das imagens?

**Comment by cabelotaina** [comment]
Acredito que o pessoal da aspta teria que inserir as imagens no tamanho exato e com o recorte especifico para esta area do site. 
É muito comum esse tipo de escolha o facebbok define o tamanho do banner, o youtube pede uma imagem especifica, sempre o tamanho deve ser seguido a risca para uma melhor esperiencia do usuário.

**Comment by rodineicosta** [comment]
Sugiro que as imagens que forem para o slideshow sejam de 1280px de largura, pois a proporção do mesmo é de 1140px de largura por 550px de altura. Vou tentar a centralização automática de imagens no código do WP, para que as imagens menores (como o caso daquela do ônibus) quando redimensionadas centralizem-se no slide.

**Comment by rodineicosta** [comment]
Tentei o código do WordPress pra centralizar a imagem no slideshow e a imagem mencionada, por ser menor (640px por 434px) quando ajustada automaticamente, fica posicionada a partir do topo e da esquerda e não aparece toda.

**Comment by rodineicosta** [comment]
Mesmo com o plugin de centralização de imagens ativado no carrossel, as imagens ainda aparecem da mesma forma. Talvez, isso somente se resolva com as imagens atendendo a padrão mínimo de tamanho (1140x550) ou maiores (1280x960).

**Comment by cabelotaina** [comment]
Pessoal acho que esta issue pode ser fechada com a ultima resposta do rodi.
