### ISSUE TITLE
(Painel wp) Edição da página contato

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#40]
A cliente solicitou uma correção na edição do texto, mas no editor ao fazer a edição o texto quebra conforme a imagem anexa.

é necessário que o código fique em uma linha e o texto na linha seguinte ao invés de criar uma coluna ao lado na edição.
![erro-contato](https://cloud.githubusercontent.com/assets/4115304/21348816/fed130f6-c695-11e6-9f31-5ddf22c0b0ec.png)

**Comment by cabelotaina** [comment]
veja se é isto?

http://aspta.beta.redelivre.org.br/falecomagente/

**Comment by thalitasejanes** [comment]
Mmmm, então, o ideal seria que na página do site ela mantivesse as colunas, apenas na edição que não, muito complicado isso? @cabelotaina

**Comment by cabelotaina** [comment]
Então voltei ao que estava, acho que neste caso o jeito é vizualizar como texto apenas.
