### ISSUE TITLE
Datas da lista de boletim (itens de campanha)

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#41]
Os itens da campanha são cadastrados todos com a data e o padrão de listas é mostrar a data, seria possível esconder a data apenas nesta listagem?

endereço da lista: http://aspta.beta.redelivre.org.br/itens-de-campanha/boletim/

**Comment by cabelotaina** [comment]
Acredito que o @rodineicosta consegue esconder a data com css, mas vale a consulta o que mano?

**Comment by rodineicosta** [comment]
Se tiver como identificar a página (template ou page), sim é possível personalizar pelo código do próprio WordPress. No mais, a identificação dos elementos nas listas é genérico.

**Comment by rodineicosta** [comment]
Analisando os boletins, percebi que essas públicações estão com a data descrita no próprio título. Por esse motivo, elas aparcem.

**Comment by rodineicosta** [comment]
Após meu último comentário que compreendi. Data omitida na página "Boletim" dos Itens de Campanha.
