### ISSUE TITLE
Textos com imagem ausente

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#42]
Algumas páginas estão gerando um espaço de imagem ausente na página como o exemplo: http://aspta.beta.redelivre.org.br/campanha/681-2/

**Comment by cabelotaina** [comment]
Tem duas saidas uma é eles definirem uma imagem destacada para cada um dos artigos que eles tem no sistema, pois apenas os que possuem imagem destacada que aparecem imagem nessa area.

Outra é a gente colocar uma imagem com o logo da aspta quando não houver imagem.

Gosto da primeira pois deixa um site bonito e esteticamente agradavel sem repetição de imagens.

Coloquei uma imagem de exemplo para demonstrar o funcionamento:

http://aspta.beta.redelivre.org.br/campanha/681-2/

**Comment by thalitasejanes** [comment]
Quando não tem imagens não seria possível ser apenas o texto? acho que seria a opção ideal

**Comment by cabelotaina** [comment]
vou ver o que consigo fazer
