### ISSUE TITLE
Temas de intervenção páginas não encontradas

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#43]
erro ao carregar as seguintes telas - construção do conhecimento, financiamento, manejo da água, manejo ecológico dos solos, monitoramento da transição, mulheres, saúde e alimentação

**Comment by cabelotaina** [comment]
Os links estão errados.

http://aspta.beta.redelivre.org.br/temas-de-intervencao/acesso-a-mercados/

vou terminar o café da manha e vejo isso.

**Comment by cabelotaina** [comment]
@thalitasejanes acho que trangênicos não existe, veja a lista com todos os temas de intervenção. Falta apenas ele. Veja com o pessoal da ASPTA se esse seria um tema novo ou se ele existia antes na revista ... qual nome teria:

http://aspta.beta.redelivre.org.br/wp-admin/edit-tags.php?taxonomy=temas-de-intervencao&post_type=campanha&s

**Comment by thalitasejanes** [comment]
Trangênicos é uma página nova sim, deve ser inserida também na biblioteca.

**Comment by cabelotaina** [comment]
Pronto agora ela consta na bibloteca:

http://aspta.beta.redelivre.org.br/temas-de-intervencao/transgenicos/

ps.: note que o erro que aparece em cima é contribua
