### ISSUE TITLE
Plugin instant article

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#44]
A cliente solicitou a ativação do plugin instant articles pela pesquisa cheguei nesse aqui, pelo que entendi funciona para otimizar a leitura através do facebook:
https://br.wordpress.org/plugins/fb-instant-articles/

**Comment by cabelotaina** [comment]
@jacsonp teria como ativar isso dei uma analisada e parece útil para jornais, revistas e blogueiros.

@thalitasejanes neste artigo tem alguns pontos a fovor e outros contra. Veja se eles já conhecem os pontos contra. Acho legal.

**Comment by jacsonp** [comment]
Esse plugin, em especial, não, dá vários erros e não fui só eu quem teve problemas com ele:
![captura de tela de 2016-12-22 12-25-01](https://cloud.githubusercontent.com/assets/3977652/21428591/e4ffc5ea-c841-11e6-817a-f85b84bec40f.png)

Links das avaliações:
https://wordpress.org/support/plugin/fb-instant-articles/reviews/?filter=1

**Comment by thalitasejanes** [comment]
Temos uma contraproposta de outro plugins que cumpre a mesma função e funciona melhor?

**Comment by jacsonp** [comment]
Teria que testar, tem o do Automattic por exemplo:
https://github.com/Automattic/facebook-instant-articles-wp/

**Comment by jacsonp** [comment]
@jacsonp não foi o link: https://github.com/Automattic/facebook-instant-articles-wp/
