### ISSUE TITLE
Atualizar  rodapé Redes e Parcerias

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#45]
As três ultimas marcas da seçao **Redes e Parcerias** na Capa do site

ANA, Agricultures e ASA para atualização.

![rede-agriculturas](https://cloud.githubusercontent.com/assets/4115304/21350397/404e261c-c69e-11e6-9672-dfbb7377dd3d.jpg)
![asa brasil_horizontal_nova](https://cloud.githubusercontent.com/assets/4115304/21350399/405000fe-c69e-11e6-9b0e-e3774ca858ee.jpg)
![ana](https://cloud.githubusercontent.com/assets/4115304/21350398/404f483a-c69e-11e6-87ca-f837f6e84510.jpg)

**Comment by rodineicosta** [comment]
Feito!
