### ISSUE TITLE
Programas locais na Home

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#46]
Os programas locais estão funcionando corretamente mas a lista de programas ficou muito grande em relação a seção eu fiz uma proposta aqui utilizando o firebug, diminui as fonte e retirei os botões de saiba mais, assim o título fica o link (no desenho o proograma contestado sinaliza a cor laranja para hover)

o player de vídeo e o ícone da revista devem ser centralizados horizontamente para se encaixarem melhor visualmente

![programas-locais](https://cloud.githubusercontent.com/assets/4115304/21352612/6c2a95e4-c6a9-11e6-8f11-105e71eacf1a.png)

.

**Comment by cabelotaina** [comment]
Legal o @rodineicosta já estava acompanhando mas com isso acho que vai ser mais tranquilo para ele.

**Comment by thalitasejanes** [comment]
no desenho acima, a fonte do título esta em 18px e do texto em 12px com entrelinhas de 12px também.

**Comment by rodineicosta** [comment]
Proponho que a descrição de cada programa seja reduzida a quatro linhas e mantem-se como está.

**Comment by thalitasejanes** [comment]
@rodineicosta é uma parte informativa, não dá pra reduzir... tentei o máximo resolver p ficar bonito e informativo. sei que muda o layout, uma adequaçaozinha que te peço!
 que cê acha? eu acho que vai ficar um bom acabamento assim...

**Comment by rodineicosta** [comment]
@thalitasejanes. Home alterada para o design anteriormente sugerido, com Programas Locais em linha e Vídeo da Semana e Revista Agriculturas abaixo.

O tamanho do vídeo, pode ser alterado através do Widget para 640x360 pixels. O único problema é que alterar no Widget, quando exibido em dispositivos móveis estrapola a tela. Pode-se definir uma alternativa de embedar o vídeo responsivamente, via código @cabelotaina.

**Comment by rodineicosta** [comment]
![image](https://cloud.githubusercontent.com/assets/15682777/21434368/2c81d714-c85b-11e6-9417-e4ed7fea46dd.png)

**Comment by thalitasejanes** [comment]
Rodi onde vc viu esta disposição?

**Comment by rodineicosta** [comment]
Feito!
