### ISSUE TITLE
Página do Programa

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#47]
As páginas do programa vão direto para a lista de últimas postagens do programa, cada programa deve ter uma página de apresentação com as últimas postagens na sidebar conforme o site atual:

[ Paraíba](http://aspta.org.br/programas/programa-paraiba/)

[Agricultura Urbana ](http://aspta.org.br/programas/programa-de-agricultura-urbana/)

[Contestado](http://aspta.org.br/programas/programa-do-contestado/)

**Comment by cabelotaina** [comment]
@thalitasejanes veja isso com eles se pode ser assim ou deve ser do jeito antigo. Acho uma boa pois o link é exatamente o mesmo. Eu vou ver se essa páginas existe em algum lugar.

**Comment by thalitasejanes** [comment]
deve ser do jeito antigo mesmo

**Comment by cabelotaina** [comment]
Sendo assim vamos precisar de um desenho do icones que estão na lateral bem como uma revisão desta página. você tem como preparar isso, no total são 4 templates as páginas mencionadas acima e esta:

http://aspta.org.br/programas/

**Comment by rodineicosta** [comment]
Os links anteriormente redirecionavam às páginas dos programas.

**Comment by thalitasejanes** [comment]
como assim @rodineicosta

**Comment by rodineicosta** [comment]
Os links, dos botões, redirecionavam para a página dos programas e não para listas de posts dos mesmos.

**Comment by cabelotaina** [comment]
@thalitasejanes você pode criar esses botões para o novo tema?

![screenshot from 2016-12-22 20-38-43](https://cloud.githubusercontent.com/assets/1827173/21442696/a57e9848-c886-11e6-9df3-9c4b673a0998.png)

**Comment by cabelotaina** [comment]
Olá pessoal segue as páginas como estão ate o momento:

http://aspta.beta.redelivre.org.br/programa-paraiba/
http://aspta.beta.redelivre.org.br/programa-do-contestado/
http://aspta.beta.redelivre.org.br/programa-de-agricultura-urbana/

vejam que apenas o menu "veja também" foi inserido o outro menu deve ser feito via widget personalizado que esta em desenvolvimento, para isso vou necessitar das imagens @thalitasejanes se não posso colocar um menu normal também, o que acha, ai o @rodineicosta estiliza isso como foi feito no menu da Revista Nova.

Outra coisa esses links não estão visculados a home ainda.

**Comment by thalitasejanes** [comment]
podemos fazer o widget que o @cabelotaina falou no padrão de widgets, apenas texto, na biblioteca optamos sem ícones e vamos manter o padrão.
![padrao-widget](https://cloud.githubusercontent.com/assets/4115304/21457732/b16c1846-c918-11e6-857e-ca2e2ce6b36e.png)

**Comment by cabelotaina** [comment]
Legal, vou implementar isso então não terminei ainda mas de todas as formas podemos fazer mais um menus sem widgets então apenas um menu comum com estilo, e isso vai permitir que eles melhorem os menus como quiserem no futuro, o que acha?

**Comment by rodineicosta** [comment]
Menus nas páginas dos programas no formato solicitado.

**Comment by rodineicosta** [comment]
@cabelotaina não encontrei o arquivo base que monta a página do programa para alterar o HTML e ajustar a sidebar.

**Comment by rodineicosta** [comment]
@cabelotaina pesquisei mais um pouco e econtrei. Resolvido!
