### ISSUE TITLE
Paginação do site

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#48]
Neste layout (ao final da lista) é possível ver o desenho da paginação do site

https://drive.google.com/file/d/0ByEoazNloy3gWlJUOGloRnBFMEU/view?usp=sharing

**Comment by cabelotaina** [comment]
Falei com o @rodineicosta que isso não esta rolando de fazer. Acho que vai ter que ficar para mais para frente neste momento não achei ainda uma alternativa para este problema, apenas a paginção comum rola com as páginas de lista criadas automaticamente pelo wordpress, Pois não existe um template onde alterar. Quando o template existe ai simm funciona de boa. @jacsonp tem alguma ideia de como podemos fazer isso.

**Comment by thalitasejanes** [comment]
em último caso rola customizar o  que aparece hoje, utilizar mesmo padrão dos botões do site.

**Comment by rodineicosta** [comment]
Mas, em algumas páginas a navegação funciona. Façam uma pesquisa qualquer e verifiquem que funciona da forma proposta.

**Comment by rodineicosta** [comment]
![image](https://cloud.githubusercontent.com/assets/15682777/21364253/2f50d04c-c6d7-11e6-8895-ef4c201cc26a.png)

**Comment by cabelotaina** [comment]
Mas @rodineicosta rola de estilizar os botoes que temos hoje?

**Comment by rodineicosta** [comment]
@cabelotaina, essa paginação que mostrei acima está funcionando em algumas páginas. Por que não funcionaria em todas? É aquele código que te passei, via Telegram, dia desses.

**Comment by cabelotaina** [comment]
Pois este tipo de paginação não é a padrão do wp.

Em qui, 22 de dez de 2016 02:29, Rodinei Costa <notifications@github.com>
escreveu:

**Comment by rodineicosta** [comment]
Feito!
