### ISSUE TITLE
Slider mobile

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#49]
O que está previsto para o slider mobile?
 Atualmente não mostra o slider e fica um espaço.

**Comment by rodineicosta** [comment]
A experiência de slidershow em mobile é ruim. O espaço deve ser pelo motivo de várias alterações posteriores que resultou no espaço residual. Vou retirar o espaço.

**Comment by thalitasejanes** [comment]
a primeira pag deste pdf tem como ela foi idealizada no layout, encontraremos juntxs uma solução?

https://drive.google.com/file/d/0ByEoazNloy3gaC1XRTNhZnpURUE/view?usp=sharing

**Comment by cabelotaina** [comment]
Bom temos que encontrar, e eu sugiro que o slide nao entre, um dos motivos é a lista de pontos negativos do plugin do facebook que mostra os conteudos do site em mobile. ele arranca quase tudo e deixa apenas a noticia pelo que eu entendi. Ele otimiza a página para melhorar a experiencia de leitura em apps mobile.

Eu penso sempre em app mobile sem isso pois acho que atrapalha a navegaçao.

**Comment by rodineicosta** [comment]
Enatão, o que decidimos?

**Comment by jacsonp** [comment]
Normalmente pega apenas a primeira do slide, ou até randômico e fica fixo

**Comment by thalitasejanes** [comment]
Eu desenhei pensando nesta referência https://anistia.org.br/?no-high

Por aqui no meu motorola funciona super bem

**Comment by rodineicosta** [comment]
Feito!
