### ISSUE TITLE
escrever o footer

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/aspta_sage#5]
colocar as informações necessárias ( de acordo com o layout) no footer, @jacsonp sugeriu usar os widgets

**Comment by rodineicosta** [comment]
Sugiro a criação de **Opções do Tema** para a inserção das informações, logotipo, ícones das redes sociais e a criação de menu de rodapé, para que tudo possa ser inserido através do painel de administração do WP.

**Comment by rodineicosta** [comment]
Feito, reduzindo o tamanho da primeira coluna e aumentando o tamanho da segundo, inserindo link para a home na logo e utilizando apenas um widget aproveitando o menu principal para ser exibido no rodapé.
