### ISSUE TITLE
Refino design - alinhamento entre títulos e sidebar

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/aspta_sage#52]
Os títulos das páginas e etc, devem estar alinhados com o título dos widgets, como esta atualmente causa um desconforto.
![alinhamento](https://cloud.githubusercontent.com/assets/4115304/22600851/91f65086-ea23-11e6-8561-4bef26ecab84.jpg)

**Comment by rodineicosta** [comment]
Feito!

**Comment by anapaulabrasa** [comment]
@rodineicosta mas continuo vendo esse desalinhamento, tipo nesta [página](http://aspta.beta.redelivre.org.br/itens-de-campanha/boletim/) 

![itendecampanha](https://cloud.githubusercontent.com/assets/2422926/22987781/183d8048-f397-11e6-85de-831e3683c76f.png)
