### ISSUE TITLE
Slider mostra mais bolinhas do que posts setados

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#54]
O slider está mostrando mais marcadores (bolinhas) do que posts (marcados como destaques).

Isso faz com que o slider fique em branco quando chega nessas bolinhas "vazias".

![bolinhas](https://cloud.githubusercontent.com/assets/2422926/22944056/aaa3d14c-f2d6-11e6-9776-9d59dead3e49.png)

**Comment by cabelotaina** [comment]
@rodineicosta eu comentei isso:


Que esta em templates/footer.php e o problema acabou. Pois estava sendo chamado duas vezes. Tem ideia do motivo?

**Comment by cabelotaina** [comment]
Fechando com uma resalva mas o problema esta resolvido.
