### ISSUE TITLE
Estilo e Categorização no widget "Tópicos recentes"

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#55]
@rodineicosta e @cabelotaina, estou visitando cada página e seção do site para padronizar as sidebar conforme a Issue #34 

Duas questões relacionadas ao widget "Tópicos recentes" que precisam ser trabalhadas:

**Estilo** 
Conforme a Thalita colocou na issue #34, este widget precisa padronizar o estilo como no widget que tá sendo usado pro BLOG PRATOS LIMPOS (widget Posts Cleans Plates AS-PTA):
![widgettopicos](https://cloud.githubusercontent.com/assets/2422926/22976692/f6d902fc-f372-11e6-90ae-dd0ee15fec45.png)
 
Mas atualmente ele apresenta este estilo:
![ultimasnoticiasaspt](https://cloud.githubusercontent.com/assets/2422926/22976734/2d975096-f373-11e6-8da4-709deb95d679.png)

**Categorização**
Implementar a possibilidade de setar categorizações - atualmente ele puxa qualquer post mais recente. Esssa necessidade se dá para páginas específicas ( @cabelotaina veja as últimas duas respostas da issue #34 e se tiver dúvidas me chama que tou à disposição!)

**Comment by rodineicosta** [comment]
@cabelotaina, precisamos filtrar as categorias para algumas páginas.

**Comment by cabelotaina** [comment]
Para quais páginas exatamente?

**Comment by anapaulabrasa** [comment]
@cabelotaina 
Compartilhando aqui as páginas de Programas e de Campanha que devem apresentar o widget lateral de posts recentes específicos. 

PROGRAMAS - págs que devem conter o widget "Últimas deste Programa":

- [Programa Paraíba](http://aspta.beta.redelivre.org.br/programa-paraiba)
- [Programa de Agricultura Urbana](http://aspta.beta.redelivre.org.br/programa-de-agricultura-urbana)
- [Programa do Contestado](http://aspta.beta.redelivre.org.br/programas/programa-do-contestado/)


CAMPANHA TRANSGÊNICOS - págs que devem conter o widget "Últimos posts da Campanha":

- [Boletim](http://aspta.beta.redelivre.org.br/itens-de-campanha/boletim/) 
- [Gm Free Brazil](http://aspta.beta.redelivre.org.br/itens-de-campanha/gm-free-brazil/)
- [Materiais de campanha](http://aspta.beta.redelivre.org.br/itens-de-campanha/materiais-de-campanha/)
- [Monitoramento da CTNBio](http://aspta.beta.redelivre.org.br/itens-de-campanha/monitoramento-ctnbio/)
- [Transgênicos](http://aspta.beta.redelivre.org.br/itens-de-campanha/campanha-transgenicos/)

Aguardo implementação para realizar novos testes.

**Comment by anapaulabrasa** [comment]
@cabelotaina 

percebi que para os programas estão utilizando a categoria Notícias mesmo, mas a categoria está atribuida a cada programa, por exemplo http://aspta.beta.redelivre.org.br/category/noticias/?programas=programa-de-agricultura-urbana

então acho que no caso dos programas não é necessário criar categoria, certo?
