### ISSUE TITLE
Arrumar espaçamento e estilo do widget da Revista

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#56]
Estou encontrando um erro relacionado ao widget IssueM Active Issue, da Revista Agriculturas. @rodineicosta se essa issue não for tua, marca o Maurilio, porfa

Em um lugar a imagem da capa da revista fica colada na linha superior alaranjada (que separa do título). Em outros lugares fica perfeito, com o devido espaçamento:

 Página [Quem Somos](http://aspta.beta.redelivre.org.br/quem-somos/)
![agriculturasquemsomos](https://cloud.githubusercontent.com/assets/2422926/22982326/025ffac8-f386-11e6-8b2f-9c866cc41e5c.png)

Página [Temas de intevenção](http://aspta.beta.redelivre.org.br/temas-de-intervencao/)
![agriulturastemasdeinterven](https://cloud.githubusercontent.com/assets/2422926/22982340/0a821196-f386-11e6-86c5-434fd4ccc988.png)

Um erro que encontrei e que deve estar relacionado a isso: na hora em que arrasto o widget para a seção que desejo utilizá-lo, acontece isto:
![widgetrevistasbug](https://cloud.githubusercontent.com/assets/2422926/22982052/149ce9e0-f385-11e6-988c-0e464b73aa0c.png)

**Comment by rodineicosta** [comment]
O erro no widget IssueM ocorre quando é inserido e aparece automaticamente com um código HTML no título. Ao substituí-lo pelo título correto "Revista Agriculturas" e salvá-lo o erro desaparece. Acredito ser um bug do próprio plugin.
