### ISSUE TITLE
Página Campanha Transg quebrando - sidebar 

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#57]
Marcando os dois aqui porque não sei de quem é a resolução, @rodineicosta e @cabelotaina 

A página [Campanha Transgênicos](http://aspta.beta.redelivre.org.br/campanha-trangenicos/) tá quebrando de modo que a sidebar vai lá pra baixo do rodapé.

![rodapecampanhatransg](https://cloud.githubusercontent.com/assets/2422926/22983988/24618100-f38b-11e6-9798-47b2000dbef4.png)

**Comment by rodineicosta** [comment]
@cabelotaina essa página não está chamando o _base-gm_campaign.php_ e sim o _base.php_, não consegui descobrir a causa. :-(

**Comment by anapaulabrasa** [comment]
parece que deu certo, né, @rodineicosta ? vc confirma e fecha essa issue? = )

**Comment by rodineicosta** [comment]
@anapaulabrasa não fechei ainda porque necessito da ajuda do @cabelotaina para que a página funcione corretamente.

**Comment by cabelotaina** [comment]
Vou ver o que acontece com essa página em breve.

**Comment by cabelotaina** [comment]
Olá notei que existe apenas 1 template que da acesso a essa página ./templates/transgenics_campaign.php dado que não existe outro acredito que as coisas estão corretas. Sendo assim vou fechar essa issue.
