### ISSUE TITLE
Erro do plugin Contribua na página Transgênicos

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#58]
Na página [Transgênicos](http://aspta.beta.redelivre.org.br/temas-de-intervencao/transgenicos/), dos Temas de intervenção, tá rolando um erro que o @cabelotaina atribuiu ao plugin Contribua

Isso seria com o @jacsonp, Maurilio?

![transplugcotr](https://cloud.githubusercontent.com/assets/2422926/22984956/2a5eb8e0-f38e-11e6-878c-c82ded6c2ae3.png)

**Comment by cabelotaina** [comment]
Olá fiz a correção mas o plugin do contribua não esta sincado com o beta por meio do jenkins, temos que esperar que o @jacsonp sinc ele por lá ou coloque ele para funcionar e ver se o problema se resolve.

**Comment by cabelotaina** [comment]
Pronto o erro não existe mais!!!!! ahhhhhhhh

**Comment by anapaulabrasa** [comment]
E nem a página, @cabelotaina! haha 
Veja http://aspta.beta.redelivre.org.br/temas-de-intervencao/transgenicos/

**Comment by cabelotaina** [comment]
Esse tema nunca teve nenhum post. Acho que ele é novo @anupamas

**Comment by anapaulabrasa** [comment]
entendi.
