### ISSUE TITLE
Revista: números anteriores inserir apenas PDF

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#60]
@cabelotaina 
Números anteriores da Revista Agriculturas vão apresentar apenas pdf para baixar. 

O numero da Revista entra como titulo do post.

**Comment by cabelotaina** [comment]
Alguém pode tirar os textos? Pois se não vou ter que entrar em cada uma e fazer isso? Como seria a solução hehehehe sorry minha pergunta meio boba...

**Comment by rodineicosta** [comment]
@cabelotaina, se forem os mesmos elementos HTML que já existem no modo atual, estão ocultos via CSS, precisando apenas exibir o título. Daí, o título de cada revista deve ser o número, quando publicada. Isso resolve?

**Comment by anapaulabrasa** [comment]
Achei que tinha entendido... mas não entendi! que texto que tem que tirar? @thalitasejanes e @cabelotaina, podem explicar e mandar um print pra mim? eu tiro

**Comment by thalitasejanes** [comment]
eu nao entendi que textos tb.

**Comment by rodineicosta** [comment]
@anapaulabrasa e @thalitasejanes, continuo sugerindo ocultar o conteúdo do post via CSS. Pois, mesmo que apague hoje, no futuro podem escrever. Daí, estando o elemento oculto, como está no momento, não correremos esse risco.

**Comment by thalitasejanes** [comment]
mas onde que esta isso, do que estamos falando?

**Comment by rodineicosta** [comment]
Nos posts das revistas.

**Comment by thalitasejanes** [comment]
manda o linque @rodineicosta

**Comment by rodineicosta** [comment]
Acredito que seja isso que o @cabelotaina esteja mencionando: [http://aspta.beta.redelivre.org.br/article/testando-artigo-1/](url)

**Comment by thalitasejanes** [comment]
a issue se refere ao historico, vc esta passando um linque do novo plugin, acho que nao eh isso, precisamos da resposta do @cabelotaina 

se não vai confundir

**Comment by rodineicosta** [comment]
E não é esse o plugin que gerará os números anteriores da revista? Em todo caso, aguardemos a resposta do @cabelotaina. ;-)

**Comment by cabelotaina** [comment]
Os conteudos possuem um link para baixar um pdf. Qual seria a tarefa neste caso? Nenhuma apenas deixamos como esta? Como tem que ficar a página?

**Comment by anapaulabrasa** [comment]
gente, tá confuso isto... @thalitasejanes não será o caso de fazermos uma conversa rápida com o @cabelotaina  pra pra vc explicar pra gente exatamente qual foi a solicitação?

**Comment by thalitasejanes** [comment]
Pessoal, eu verifiquei é uma anotação sobre o **historico de revistas** que estão no formato anterior (nao o plugin issueM), vamos colocar as miniaturas das capas e para baixar o pdf, nao sei se no formato post ou fazer uma pagina mesmo.

Numeros anteriores será gerado com o plugin IssueM

**Comment by cabelotaina** [comment]
Legal @thalitasejanes e onde o usuário vai encontrar isso, no menu do topo? no rodapé? Em que lugar?

**Comment by rodineicosta** [comment]
Não seria no submenu interno da Revista?

**Comment by thalitasejanes** [comment]
@anapaulabrasa @cabelotaina @rodineicosta 

Como a revista vai mudar de formato a partir de agora - utilizando o plugin issueM -, tinhamos ficado de aprovar com a Adriana como seriam mostradas as revistas anteriores ao plugin (que atualmente são mostradas com o Issu [veja aqui](http://aspta.org.br/revista-agriculturas/).

a Adriana aprovou a ideia de colocar as capas da revista num pdf simples e sair do issue

temos uma escolha a fazer ou abrimos uma aba Histórico no menu da revista, ou inserimos esta seção na página numeros anteriores do site [veja aqui](http://aspta.beta.redelivre.org.br/numeros-anteriores/), 
digo inserir a seção, pois este é o historico gerado pelo novo plugin com as revistas já no novo formato.

Podemos marcar um papo se não ficou claro.

**Comment by cabelotaina** [comment]
Qual das duas formas você acha que fica melhor?

**Comment by thalitasejanes** [comment]
nós propusemos pdf e a cliente aprovou, eu acho que essa é melhor que o ISSU com certeza.

**Comment by thalitasejanes** [comment]
Gente eu fiz um esquema da demanda aqui 
![revista-edicoes-anteiores](https://cloud.githubusercontent.com/assets/4115304/24292707/403914a2-106d-11e7-8a93-c0552b470a23.png)

**Comment by thalitasejanes** [comment]
o grande desafio de deixar na mesma lista é que as cadastradas como historico deve estar antes das revistas geradas pelo plugin, mas caso seja necessário abrimos a aba historico

**Comment by cabelotaina** [comment]
Acho que rola de colocar a area gerada automaticamente pelo plugin usando shortcodes:

https://zeen101.com/documentation/shortcodes/

**Comment by cabelotaina** [comment]
No momento temos apenas essa issue. É Isso mesmo?
