### ISSUE TITLE
Inserir botão de assinatura da Revista na home 

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#62]
@cabelotaina 

Na capa, de preferência abaixo da miniatura da Revista, inserir o botão de [assinatura](http://aspta.beta.redelivre.org.br/revista-agriculturas/mobilize/)

**Comment by rodineicosta** [comment]
Feito!

**Comment by anapaulabrasa** [comment]
o ruim é que deu uma aumentada nervosa nesse box, né =/ veja a imagem ali embaixo

alguma sugestão, @thalitasejanes? 

Acho que: 
1º - a gente tinha que se esforçar pra manter um alinhamento dos três elementos (textos de programas; e vídeo e revista) nem que eles tenham que dar uma diminuida.
2º acho que teria que colocar uma altura máxima nesse box, pra ele não esticar independente do conteúdo (mas é só um pitaco, não sei se isso é possível).

![botaoassinerevist](https://cloud.githubusercontent.com/assets/2422926/23024255/84ed1ec0-f440-11e6-8878-404b75826298.png)

**Comment by anapaulabrasa** [comment]
Talvez também transformar em botão esse "Assista aos vídeos da AS-PTA", e aí colocar abaixo do vídeo, daria uma ajuda, linkando para a página do youtube deles

**Comment by rodineicosta** [comment]
Falta aparecer um dos três programas do lado esquerdo. Quando inseri o botão, reduzi o tamanho da revista, para que ficasse como estava. O vazio que percebo existir é na parte do vídeo. Por isso, anteriormente, eu propus um layout diferente para que o vídeo pudesse ocupar uma largura maior e consequentemente altura também. A ideia do botão pro vídeo é uma boa. Mas, ainda assim, removeria o texto de cima.

**Comment by anapaulabrasa** [comment]
Verdade, falta um dos programas... Tá faltando o que pra ele entrar, uma descrição?

**Comment by rodineicosta** [comment]
Nesse caso, só o @cabelotaina pode nos dizer.
