### ISSUE TITLE
Mobile: plugin pra deixar mais leve o compartilhamento

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/aspta_sage#63]
Registrando aqui o que o @cabelotaina colocou como comentário do docs. 
Maurílio, você solicitou direito com o Jacson pra ele colocar no beta?

Maurilio Santana
17:55 1 de fev
Vou pegar ele e instalar local e ver como fica esse modulo. Espero que role local hehehe.

Maurilio Santana
18:12 1 de fev	
Olá pessoal funciona assim, temos que criar um app key e um app id para o app no facebbok ativar oi plugin seguir os passos e dizer qual a página que esta ligada ao plugin, depois ao fim tem um editor de estilo parecido com o que divi fez para modificar a home (div 2). Sendo assim vamos precisar do usuário e senha dá pagina da ASPTA no facebook. Para criar o app id e o app key e selecionar a página deles como base do plugin. é isso. Acho que isso posso fazer junto com a Thalita, Anupamas e Rodi. Se Jack estiver com ganas de ver é mais do que bem vindo :)

Maurilio Santana
20:27 1 de fev
o @jacsonp  teria que colocar o plugin no beta para a gente fazer a configuração

**Comment by cabelotaina** [comment]
Eu adicionari o modulo como o @jacsonp  me disse para fazer, mais uma vez, vamos ver e com esse funcionar pois com o plugin de eventos não rolou. rolando isso posso fazer uma conf fake por principio. Mas precisamos do usuário senha da conta deles para testar e configurar com o original.

Pode pedir para eles e me enviar em privado @thalitasejanes. Basicamente é usuário e senha da conta do aspta no facebook ou me dar acesso de admin na página deles. Se for uma página.

**Comment by anapaulabrasa** [comment]
certo. já passei o perfil da adriana pro @cabelotaina. assim q ele add, eu aviso a adriana pra aceitar e adicionar como admin da pagina da ASPTA no face

**Comment by cabelotaina** [comment]
Olá ate o presente momento eu não fui adicionado como admin na página da aspta no facebook. @anapaulabrasa veja com a Adriana se ela pode ver o que aconteceu.

**Comment by cabelotaina** [comment]
O plugin esta instalado. Temos o acesso a página da ASPTA, falta instalar as dependencias do plugin como em https://github.com/Automattic/facebook-instant-articles-wp#installation

**Comment by cabelotaina** [comment]
enviei para revisao do facebook o estilo.
