### ISSUE TITLE
SUBMENU Revista ASPTA

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#66]
O Sub-menu da lateral direita na página da "[Revista Agriculturas](http://aspta.redelivre.org.br/revista-atual/)¨ deve permanecer quando clicamos nas páginas internas, de modo que o usuário possa continuar navegando 
![revistaaspta](https://user-images.githubusercontent.com/4163139/29801362-8e818a96-8c45-11e7-975f-5ea549d17d8e.png)

**Comment by cabelotaina** [comment]
Inseri nas paginas que possuem widgets

**Comment by jpmehl** [comment]
Mas isto gerou um problema: 

Agora este widget de menu aparece encima na página do QUEM SOMOS e aparece quebrado na página Campanha Transgênicos: http://aspta.redelivre.org.br/campanha-trangenicos/

Minha sugestão aqui é de apenas aparecer nas sub-paginas da Revista Agriculturas: 
    Sobre a Revista
    Números Anteriores
    Próximas Chamadas
    Submeter Artigo
    Assine

**Comment by cabelotaina** [comment]
Certo, vou tirar, mas coloquei porque ententi "páginas internas" como todas as paginas menos a home.

**Comment by cabelotaina** [comment]
Certo defiz isso vou como colocar o widget nas paginas

**Comment by cabelotaina** [comment]
A pagina assine usa o template do mobilize, se colocamos o template da revista o mobilize nao funciona por isso neste caso teria que codar algo, nao eh um problema de configuracao, por isso vou fechar aqui e abrir uma nova somente para isso,

Ja modifiquei de todas as outras.
