### ISSUE TITLE
Widget Revista ASPTA

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#67]
Tanto na capa quanto nas internas, o widget da Revista ASPTA não está funcionando, aparece um image not found:

![widget-revista-aspta](https://user-images.githubusercontent.com/4163139/29801409-d89aacb6-8c45-11e7-9835-9adeb33f8c27.png)

**Comment by cabelotaina** [comment]
A parte de insercao do conteudo da nova Revista penso que tenha que ser inserida pelo pessoal da ASPTA, nao seriamos nos que vamos produzir o conteudo que esta vigente, podemos colocar a ultima revista mas eles de todas as  formas precisam nos passar esses dados para nos.

**Comment by jpmehl** [comment]
Sim, mas esta issue eu criei só pra apresentar o problema do widget. Sobre a revista e seu funcionamento, criei outra issue.

**Comment by cabelotaina** [comment]
Ah ta eh o seguinte a imagem aparece assim pois nao colocamos nenhuma revista, ja que nao fizemos uma sincronizacao com a aspta de qual revista deviamos colocar (principiantes), mas neste caso podemos ver com eles essas infos, vc consegue facilitar esse processo?

**Comment by cabelotaina** [comment]
Bom coloquei la para exemplo, por algum motivo depois da importacao estava com zero artigos e sem imagem, apenas coloquei uma imagem e vinculei artigos e ai esta:

<img width="528" alt="imagen" src="https://user-images.githubusercontent.com/1827173/29803121-229c26c8-8c50-11e7-8d10-396a9a17723a.png">

<img width="424" alt="imagen" src="https://user-images.githubusercontent.com/1827173/29803130-30551ca2-8c50-11e7-94f3-592f6b08a9a1.png">

http://aspta.redelivre.org.br/
