### ISSUE TITLE
Programas locais na capa

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#68]
Os programas locais na capa não estão aparecendo: 

![programas-locais-aspta](https://user-images.githubusercontent.com/4163139/29801438-fff179e8-8c45-11e7-9487-4579662e245a.png)

**Comment by cabelotaina** [comment]
Salve aqui eh o seguinte os programas nao foram importados:

<img width="836" alt="imagen" src="https://user-images.githubusercontent.com/1827173/29803391-cba29ac6-8c51-11e7-881b-487f85e2bd82.png">

<img width="845" alt="imagen" src="https://user-images.githubusercontent.com/1827173/29803394-d778b83a-8c51-11e7-8d30-6a6a00244856.png">

http://aspta.redelivre.org.br/wp-admin/edit-tags.php?taxonomy=programas
http://aspta.beta.redelivre.org.br/wp-admin/edit-tags.php?taxonomy=programas

@jacsonp tem alguma ideia de como poemos pegar essa info?

**Comment by jpmehl** [comment]
Algum avanço aqui?

**Comment by cabelotaina** [comment]
Mandei mensagem para o jack para saber se ele pode ver o que aconteceu com a importacao das taxonomias.

**Comment by jacsonp** [comment]
Feito, foi preciso 6 horas de trabalho aproximadamente, com por exemplo o desenvolvimento de um plugin para o wp-cli
https://github.com/jacsonp/wp_cli_countfix
![image](https://user-images.githubusercontent.com/3977652/30349810-b58194e6-97ea-11e7-9320-9de4d3b6680d.png)
Porem, aparentemente isso não resolveu o problema

**Comment by cabelotaina** [comment]
<img width="423" alt="imagen" src="https://user-images.githubusercontent.com/1827173/30352813-8a9ac9b0-97f8-11e7-9fc5-ddc68a2e4c4b.png">
perfect @jacsonp! tu eh o cara.

fechando!
