### ISSUE TITLE
Equipe executiva e-mails errados

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#69]
Não sei por qual motivo que na página equipe executiva, o e-mail aparece o beta.ethymos....:
http://aspta.redelivre.org.br/quem-somos/equipes-de-trabalho/

![equipe-executiva-aspta](https://user-images.githubusercontent.com/4163139/29801500-52eaf7aa-8c46-11e7-920c-0f8e3570f37a.png)

**Comment by cabelotaina** [comment]
Pronto corrigido -> http://aspta.redelivre.org.br/quem-somos/equipes-de-trabalho/

Acredito que isso tenha a ver com uma funcao que normalmente usamos para alterar as urls internas quando eh feita a migracao de um site para outro dominio, mas eh apenas um chute, como isso eh passado no banco ele deve ter alterado isso ja que devia estar batendo com a url buscada, olha so no que deu.
