### ISSUE TITLE
Pägina quem somos 

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#70]
Não sei a que pé anda a importação, mas na página do QUem Somos, nenhuma documentação foi importada: http://aspta.org.br/quem-somos/

**Comment by cabelotaina** [comment]
Complementei com os enderecos que estavam faltando
http://aspta.redelivre.org.br/quem-somos/

**Comment by jpmehl** [comment]
Este são os endereços, mas os documentos não foram importados: 
http://aspta.redelivre.org.br/quem-somos/planos-trienais/
http://aspta.redelivre.org.br/quem-somos/relatorios-de-atividades/
http://aspta.redelivre.org.br/quem-somos/estatutos-e-atas/
http://aspta.redelivre.org.br/quem-somos/balanco-patrimonial/

**Comment by cabelotaina** [comment]
Eu estava falando destes enderecos aqui

<img width="304" alt="imagen" src="https://user-images.githubusercontent.com/1827173/29802140-e0929060-8c49-11e7-9ca9-2cd8328753db.png">

Nao destes de cima, esses nem tinha visto...

**Comment by cabelotaina** [comment]
Fiz balanco patrimonial:
http://aspta.redelivre.org.br/quem-somos/balanco-patrimonial/

**Comment by cabelotaina** [comment]
Feito: http://aspta.redelivre.org.br/quem-somos/relatorios-de-atividades/

**Comment by cabelotaina** [comment]
feito http://aspta.redelivre.org.br/quem-somos/estatutos-e-atas/

**Comment by jacsonp** [comment]
![image](https://user-images.githubusercontent.com/3977652/29802499-e78794cc-8c4b-11e7-9719-4c7d31c6a133.png)
sidebar dessa área está correta?

**Comment by cabelotaina** [comment]
feito: http://aspta.redelivre.org.br/quem-somos/planos-trienais/

**Comment by cabelotaina** [comment]
Poxa isso nao sei dizer jack, mas acho o revista pelo que estou entendendo deve aparecer em todo o site. Eh isso, quando a imagem isso temos que ver com o cliente pois nao sabemos em que pe esta a revista e precisamos que o tive de design da revista entre full no site, assim podemos saber como ajudar. Se nao corremos o risco de tentar fazer o esse papel de colocar a revista no site e nao sabemos fazer isso. Fazer errado.

**Comment by cabelotaina** [comment]
Vou fechar considerando que o tema da issue foi coberto, jack abra essa issue da sua pergunta mnovamente. tks

**Comment by jacsonp** [comment]
não precisa, o bug que reportei nessa issue é duplicação do #67, confirmei com testes
