### ISSUE TITLE
Limitar tamanho da imagem do slider

### ISSUE THREAD

**Issue by jacsonp** [redelivre/aspta_sage#73]
Fazer o crop (max-height) da imagem no slider para evitar que isso aconteça:
![image](https://user-images.githubusercontent.com/3977652/29828712-ed349fba-8cb3-11e7-8c25-33fae0f408fd.png)

**Comment by rodineicosta** [comment]
Questão já resolvida na Issue #39.

**Comment by jacsonp** [comment]
Não é a mesma issue, na #39 fala de imagem distorcida, aqui estou falando da área distorcida, está comendo o título da notícia, falo para forçar um max-height para a área, pode ser que também rola o wontfix para essa issue

**Comment by rodineicosta** [comment]
Aqui, aparece normal.

![image](https://user-images.githubusercontent.com/15682777/29829505-fecbd66a-8cb5-11e7-8f47-90ab52f9c4eb.png)

**Comment by jacsonp** [comment]
Agora para mim ficou normal também, vou fechar, se voltar a ficar estranho reabro
