### ISSUE TITLE
Vídeo da capa está cortado

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#75]
Conforme anexo, o vídeo da capa está cortado. 

![video-aspta-capa](https://user-images.githubusercontent.com/4163139/29937859-496bda78-8e5d-11e7-86aa-16808a6aabe5.png)

**Comment by rodineicosta** [comment]
O tamanho do vídeo é definido no _iframe_ que está com as dimensões de 360x320. Mas, por algum motivo o vídeo está sendo exibido nas dimensões 360x150. Vou investigar. Eu tinha comentado anteriormente que as proporções do vídeo nessa área não ficariam perfeitas, deixando espaços vazios em relação as colunas ao lado.

**Comment by jpmehl** [comment]
Alguma novidade?

**Comment by cabelotaina** [comment]
Olhei agora a home e o video esta ok, acho que o conteudo de programas locais nao estar presente pode ter causado o problema.

<img width="1232" alt="imagen" src="https://user-images.githubusercontent.com/1827173/30352848-c729a2de-97f8-11e7-8d01-94669429d0ab.png">

Acredito que neste caso podemos fechar essa issue. Vou fechar ela @jpmehl se achar pertinente reabre ela aqui.
