### ISSUE TITLE
Menu tem que ter a página de PROGRAMAS

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#77]
A página de programas precisa estar no MENU, e a página interna tem que ter os três programas.

**Comment by rodineicosta** [comment]
Se entrar mais um item no menu, o mesmo ficará desproporcional. A não ser que se exclua um em substituição (ex.: Assine o Feed).

**Comment by jpmehl** [comment]
Eu já fiz isto, tá resolvido.
