### ISSUE TITLE
Página Transgênicos em temas de intervenção vazia

### ISSUE THREAD

**Issue by jpmehl** [redelivre/aspta_sage#80]
Página com problema: http://aspta.redelivre.org.br/temas-de-intervencao/transgenicos/

**Comment by cabelotaina** [comment]
@thalitasejanes confirma se isso eh uma pagina nova ou se ela ja existia, lembro que vc me disse uma vez que tal coisa eh nova.

**Comment by cabelotaina** [comment]
Serguinte de fato a pagina nao deve existir como a @thalitasejanes explica nessa issue #43:

<img width="794" alt="imagen" src="https://user-images.githubusercontent.com/1827173/30352961-952dad92-97f9-11e7-9416-b1e83951f7f1.png">

**Comment by jpmehl** [comment]
@cabelotaina a mensagem da thalita diz que a página deve existir sim, leia novamente ;)

**Comment by cabelotaina** [comment]
Sim, eu entendi o mesmo que vc, mas ela diz que ela deve ser inserida, mas ela nao possui conteudo por isso nao aparece nada. Ou seja nao existe conteudo. So me expressei mau. rs
